@startuml
skinparam componentStyle uml2

package "Physical Machine" as physical {
    make_blk_device.sh as makeBlkDevice
    () var_lib_docker.img as dockerImg
    makeBlkDevice --> dockerImg : creates and formats as btrfs
    setup_blk_device.sh as setupBlkDevice
    run.sh as runScript
    [docker daemon] as outerDocker
    runScript --> outerDocker : tells to start proxy container
    outerDocker --> proxy : runs
    database "/dev/loop0" as loop0
    package "Physical Machine Proxy Container (fairly high privileges)" as proxy {
        [systemd]
        database "/dev/loop0" as loop0.1
        loop0 <.. loop0.1 : passed in via docker command line
        component kataDocker [
            docker daemon
            (can run kata containers)
        ]
        systemd --> kataDocker : launches
        package "Kata Container (offers full VM isolation)" as kataContainer {
            database "/dev/loop0" as loop0.2
            loop0.1 <.. loop0.2 : passed in via docker command line
            () "/var/lib/docker" as varLibDocker
            loop0.2 <.. varLibDocker : backing device

            [systemd] as nestedSystemd
            component "docker daemon" as nestedDocker
            varLibDocker ..> nestedDocker : storage for all images and containers
            package "Isolated container (fairly restricted privileges)" as isolatedContainer {
                [your isolated process] as isolatedProcess
            }
        }
        kataDocker --> kataContainer : launches
        nestedSystemd --> nestedDocker : launches
        nestedDocker --> isolatedContainer : launches
    }
    setupBlkDevice ..> dockerImg : configures as block device loop0
    dockerImg <.. loop0 : backing file
}

@enduml